(module (memory 1)
  (func $loop (result i32)
    (local $x i32) (local $y i32) (local $i i32) (local $addr i32)
    (set_local $x (i32.const 5))
    (set_local $y (i32.const 7))
    (set_local $i (i32.const 0))
    (set_local $addr (i32.const 1024))
    (i32.store (get_local $addr) (i32.const 0))
    (block
      (loop
        (get_local $addr)
        (i32.load (get_local $addr))
        (get_local $x)
        (i32.add)
        (get_local $y)
        (i32.add)
        (i32.store)
        (get_local $i)
        (i32.const 1)
        (i32.add)
        (set_local $i)
        (br_if 1 (i32.eq (get_local $i) (i32.const 1000)))
        (br 0)
      )
    )
    (i32.load (get_local $addr))
  )
  (export "loop" (func $loop))

   (func (export "_main") (result i32)
      (call $loop)
   )
)